import Foundation
import SwiftUI
import Observation
import Network

/// Owns the live SSH session and its terminal surface. Bridges:
///
///   SSHClient  ─── onOutput ───→ LibGhosttyTerminalController.write
///   LibGhosttyTerminalController.onInput (terminal-generated bytes)
///   TerminalInputView.onBytes ─── write ───→ SSHClient.write
///   LibGhosttyTerminalController.onResize ─── resize ───→ SSHClient.resize
///
/// Also owns the auto-reconnect state machine: an unexpected SSH drop
/// (network blip, server restart, sleeping Mac waking, etc.) triggers
/// an exponential-backoff retry loop. A path monitor reacts immediately
/// to network re-availability so the user gets back to live as soon as
/// the radio comes back. tmux on the remote preserves the session, so
/// a successful reconnect lands the user exactly where they left off.
@Observable
@MainActor
final class SessionViewModel {

    enum ConnectionState: Equatable {
        case idle
        case connecting
        case connected
        case reconnecting
        case disconnected(reason: String?)
    }

    let terminal: LibGhosttyTerminalController
    private(set) var state: ConnectionState = .idle
    private(set) var hostName: String
    /// Multi-session index: 0 = primary tmux session, 1+ = additional
    /// concurrent sessions on the same host. Drives the tmux session name
    /// so they don't collide.
    let sessionIndex: Int
    /// Explicit tmux session name, e.g. `shio-<project>` or `shio-<host>`.
    let tmuxSessionName: String
    /// Directory to open the session in (the repo path for a project
    /// session), or nil to start in the login shell's default.
    let startDirectory: String?
    /// For projects created from a git URL: the URL to clone into
    /// `startDirectory` on first open (guarded — only if it doesn't exist).
    let cloneURL: String?
    var targetPort: Int { configuration.port }

    private var client: SSHClient?
    private var configuration: SSHClient.Configuration
    private let persistenceMode: Host.PersistenceMode
    private var tmuxFallbackTriggered = false

    // MARK: Host-key review
    /// True when the last failure was a refused host-key change — drives the
    /// "Review key change" affordance on the disconnected overlay.
    private(set) var hostKeyConflict = false
    /// The pin-store key for this session's endpoint (matches the format the
    /// validation delegate records under).
    var hostPort: String { "\(configuration.host):\(configuration.port)" }
    /// What changed, for the review dialog (pinned vs offered fingerprint).
    var hostKeyMismatch: ShioKnownHosts.Mismatch? { ShioKnownHosts.mismatch(for: hostPort) }

    /// The user reviewed the refused change and chose to trust the new key:
    /// drop the pin (TOFU re-pins on the next connect) and reconnect.
    func trustNewHostKeyAndReconnect() {
        ShioKnownHosts.forget(hostPort)
        hostKeyConflict = false
        Task { await start() }
    }

    // MARK: Resize debounce
    /// Latest grid size waiting to be pushed to the remote PTY.
    private var pendingResize: (cols: Int, rows: Int)?
    /// The last size the view reported, kept after `pendingResize` is consumed.
    /// A control-mode client renders for itself, so tmux knows no size until it
    /// is told one on attach.
    private var lastSize: (cols: Int, rows: Int)?
    /// Coalesces the burst of resize callbacks that fire during rotation,
    /// split-view drags, and keyboard show/hide. libghostty re-renders
    /// locally on every change immediately; we only debounce the SIGWINCH to
    /// the remote so the shell/TUI isn't thrashed mid-animation.
    private var resizeDebounce: Task<Void, Never>?

    // MARK: Control mode
    /// Live when this connection is speaking `tmux -CC` instead of raw bytes.
    ///
    /// Opt-in for now (Settings → Terminal). The transport is the risky half of
    /// control mode and this proves it against a real session before the UI is
    /// restructured around tmux's panes; with one pane the two paths should be
    /// indistinguishable, which is exactly what makes it testable.
    private var control: TmuxControlSession?
    /// Which pane's bytes belong on screen. Until the UI models panes, that is
    /// whichever tmux says is active.
    private var renderedPaneID: String?
    /// Bytes seen before the handshake completed, kept so they can still be
    /// drawn if it turns out nothing is speaking the protocol.
    private var controlWarmup: [UInt8] = []
    private var controlHandshake: Task<Void, Never>?

    // MARK: Session identity
    /// Set by `SessionStore` so the Live Activity can be keyed by the owning
    /// session's id.
    var ownerSessionID: UUID?

    // MARK: Link detection
    /// The most recent http(s) URL seen in output, surfaced so the user can
    /// open it in an in-app browser — chiefly for CLIs (Claude Code login,
    /// `gh auth`, etc.) that would otherwise open a browser on the remote
    /// machine you can't reach from your phone. Cleared by the UI once used.
    private(set) var detectedURL: URL?
    private static let urlRegex = try? NSRegularExpression(
        pattern: "https?://[^\\s\"'<>)\\]}]+", options: [])

    // MARK: Reconnect state

    /// True once the user (or the parent view's onDisappear) explicitly
    /// closed the session. Suppresses auto-reconnect so we don't fight
    /// the user trying to leave.
    private var userInitiatedStop = false
    /// Current reconnect attempt count. Reset on a successful connect.
    private var reconnectAttempt = 0
    /// Task running the backoff loop. Cancellable so a path-change can
    /// short-circuit the wait. Backoff/attempt-budget/permanent-failure rules
    /// live in the shared `ReconnectPolicy` (the Mac runs the same table).
    private var reconnectTask: Task<Void, Never>?

    // MARK: Network monitor

    /// Watches for path changes (WiFi → cellular, network return, etc.)
    /// so we can react to connectivity events rather than just polling
    /// via the backoff.
    private let pathMonitor = NWPathMonitor()
    private let monitorQueue = DispatchQueue(label: "sh.shio.session.path")
    private var lastPathSatisfied: Bool = true
    /// The interface the connection was last riding (WiFi / cellular / wired).
    /// A change while we believe we're connected means the old socket is dead,
    /// so we reconnect immediately instead of waiting for the TCP timeout.
    private var lastPrimaryInterface: NWInterface.InterfaceType?

    init(
        configuration: SSHClient.Configuration,
        persistenceMode: Host.PersistenceMode = .tmuxAutoResume,
        sessionIndex: Int = 0,
        tmuxSessionName: String? = nil,
        startDirectory: String? = nil,
        cloneURL: String? = nil
    ) {
        self.configuration = configuration
        self.hostName = configuration.host
        self.persistenceMode = persistenceMode
        self.sessionIndex = sessionIndex
        self.tmuxSessionName = tmuxSessionName
            ?? TmuxResume.sessionName(for: configuration.host, index: sessionIndex)
        self.startDirectory = startDirectory
        self.cloneURL = cloneURL
        self.terminal = LibGhosttyTerminalController()
        wire()
        startPathMonitor()
    }

    private func wire() {
        terminal.onInput = { [weak self] data in
            guard let self else { return }
            // In control mode the channel carries a protocol, not a keystream,
            // so raw bytes would be read as tmux commands. Before the first
            // layout arrives there is no pane to type into, and dropping the
            // keystroke is the only safe answer — writing it raw would hand
            // whatever was typed to tmux as a command line.
            if let control = self.control {
                guard let pane = self.renderedPaneID else { return }
                control.sendKeys(Array(data.utf8), toPane: pane)
            } else {
                self.client?.write(data)
            }
        }
        terminal.onResize = { [weak self] cols, rows in
            self?.scheduleResize(cols: cols, rows: rows)
        }
        terminal.onLoadFailure = { [weak self] message in
            self?.state = .disconnected(reason: message)
        }
    }

    /// Point the SSH channel at the control-mode protocol instead of the
    /// renderer. tmux stops drawing a screen and starts describing one, so the
    /// bytes on the wire are events — pane output, window changes — rather than
    /// something a terminal can render directly.
    private func setUpControlMode(client: SSHClient) {
        let session = TmuxControlSession()
        control = session
        renderedPaneID = nil

        session.send = { [weak client] line in client?.write(line) }

        session.onPaneOutput = { [weak self] pane, bytes in
            guard let self else { return }
            // Until the UI models panes, only the active one is on screen.
            // Output from a background pane is tmux keeping other clients in
            // sync and must not be interleaved into this view.
            guard pane == self.renderedPaneID else { return }
            let data = Data(bytes)
            self.terminal.write(data)
            self.detectLatestURL(in: Self.stripANSI(String(decoding: data, as: UTF8.self)))
        }

        session.onStarted = { [weak self] in
            guard let self else { return }
            self.controlHandshake?.cancel()
            self.controlWarmup = []
            // tmux sizes itself to this client only when told, and describes its
            // panes only when asked. Neither happens on its own.
            if let size = self.lastSize { session.resize(cols: size.cols, rows: size.rows) }
            session.requestLayout()
        }

        session.onLayoutChanged = { [weak self] in
            guard let self, let active = self.control?.activePaneID else { return }
            guard self.renderedPaneID != active else { return }
            self.renderedPaneID = active
            // Attaching to a session that already exists delivers no screen at
            // all — tmux forwards what happens next, not what is already there.
            // Asking for the pane's contents is what makes a phone join the
            // Mac's work mid-flight instead of opening on a blank rectangle.
            self.control?.capturePane(active)
        }

        session.onPaneRestore = { [weak self] pane, lines in
            guard let self, pane == self.renderedPaneID else { return }
            // tmux pads the capture out to the pane's height; those trailing
            // blanks would push the prompt up off the bottom and leave the
            // cursor stranded below it.
            var body = lines
            while let last = body.last, last.trimmingCharacters(in: .whitespaces).isEmpty {
                body.removeLast()
            }
            self.terminal.write(Data("\u{1B}[H\u{1B}[2J".utf8))
            self.terminal.write(Data(body.joined(separator: "\r\n").utf8))
        }

        session.onExit = { [weak self] reason in
            guard let self else { return }
            self.state = .disconnected(reason: reason ?? "tmux exited")
        }
    }

    /// Give up on control mode if nothing answers the handshake.
    ///
    /// The attach line falls back to a plain login shell when tmux is missing,
    /// and a plain shell's output fed to a protocol parser renders as nothing at
    /// all. A blank terminal that reports no error is the worst failure Shio
    /// has: it looks like the network, or the host, or the app. So when the
    /// handshake does not land, stop parsing and draw what actually arrived.
    private func startControlHandshakeWatchdog() {
        controlHandshake?.cancel()
        controlHandshake = Task { [weak self] in
            try? await Task.sleep(nanoseconds: 5_000_000_000)
            guard let self, !Task.isCancelled,
                  let control = self.control, !control.isSynced else { return }
            self.control = nil
            self.renderedPaneID = nil
            let buffered = self.controlWarmup
            self.controlWarmup = []
            if !buffered.isEmpty { self.terminal.write(Data(buffered)) }
            self.terminal.write(Data("\r\n\u{1B}[33m[shio] tmux control mode didn't answer — plain shell.\u{1B}[0m\r\n".utf8))
        }
    }

    /// Strip ANSI/VT escape sequences and carriage-return overwrites so URL
    /// detection sees plain text.
    private static func stripANSI(_ s: String) -> String {
        var out = s
        // CSI sequences: ESC [ … final-byte
        out = out.replacingOccurrences(
            of: "\u{001B}\\[[0-9;?]*[ -/]*[@-~]",
            with: "", options: .regularExpression)
        // OSC sequences: ESC ] … BEL  or  ESC ] … ST
        out = out.replacingOccurrences(
            of: "\u{001B}\\][^\u{0007}\u{001B}]*(\u{0007}|\u{001B}\\\\)",
            with: "", options: .regularExpression)
        // Other two-byte escapes.
        out = out.replacingOccurrences(
            of: "\u{001B}[@-Z\\\\-_]",
            with: "", options: .regularExpression)
        // Carriage returns (progress-bar overwrites) → newlines.
        out = out.replacingOccurrences(of: "\r", with: "\n")
        return out
    }

    /// Scan a freshly arrived (ANSI-stripped) chunk for an http(s) URL and
    /// surface the last one found. Trailing punctuation is trimmed so a URL
    /// printed at the end of a sentence still opens cleanly.
    private func detectLatestURL(in chunk: String) {
        guard let regex = Self.urlRegex else { return }
        let range = NSRange(chunk.startIndex..., in: chunk)
        let matches = regex.matches(in: chunk, range: range)
        guard let last = matches.last, let r = Range(last.range, in: chunk) else { return }
        var candidate = String(chunk[r])
        while let trailing = candidate.last, ".,;:".contains(trailing) { candidate.removeLast() }
        if let url = URL(string: candidate), url != detectedURL {
            detectedURL = url
        }
    }

    /// Called by the UI after opening (or dismissing) the surfaced link.
    func clearDetectedURL() { detectedURL = nil }

    /// If `url` is an OAuth link whose redirect targets the host's loopback
    /// (`localhost:PORT`), open an SSH local forward for that port so the
    /// in-app browser's redirect tunnels back to the host's callback server
    /// and the login completes. Returns the forward to keep alive until the
    /// browser closes, or nil when no forward is needed/possible.
    func prepareLoopbackForward(for url: URL) async -> SSHPortForward? {
        guard case .connected = state, let client else { return nil }
        guard let port = Self.loopbackRedirectPort(in: url) else { return nil }
        return try? await client.openLocalForward(localPort: port, remotePort: port)
    }

    /// Pull a loopback callback port out of an auth URL — from a
    /// `redirect_uri`/`callback` query item, or the URL itself if it's a
    /// localhost link.
    private static func loopbackRedirectPort(in url: URL) -> Int? {
        if isLoopbackHost(url.host), let port = url.port { return port }

        guard let comps = URLComponents(url: url, resolvingAgainstBaseURL: false),
              let items = comps.queryItems else { return nil }
        let keys = ["redirect_uri", "redirect", "callback", "callback_url", "return_to"]
        for item in items where keys.contains(item.name.lowercased()) {
            guard let raw = item.value else { continue }
            let decoded = raw.removingPercentEncoding ?? raw
            if let inner = URLComponents(string: decoded), isLoopbackHost(inner.host), let port = inner.port {
                return port
            }
        }
        return nil
    }

    private static func isLoopbackHost(_ host: String?) -> Bool {
        host == "localhost" || host == "127.0.0.1" || host == "[::1]" || host == "::1"
    }

    /// Debounce remote PTY resizes (~120ms trailing). The last size in a
    /// burst wins, so a rotation that sweeps through intermediate grid sizes
    /// sends a single window-change to the remote.
    private func scheduleResize(cols: Int, rows: Int) {
        pendingResize = (cols, rows)
        lastSize = (cols, rows)
        resizeDebounce?.cancel()
        resizeDebounce = Task { [weak self] in
            try? await Task.sleep(nanoseconds: 120_000_000)
            guard let self, !Task.isCancelled, let size = self.pendingResize else { return }
            if let control = self.control {
                control.resize(cols: size.cols, rows: size.rows)
            } else {
                self.client?.resize(cols: size.cols, rows: size.rows)
            }
            self.pendingResize = nil
        }
    }

    private func startPathMonitor() {
        pathMonitor.pathUpdateHandler = { [weak self] path in
            let isSatisfied = (path.status == .satisfied)
            let primary = SessionViewModel.primaryInterface(of: path)
            Task { @MainActor [weak self] in
                guard let self else { return }
                let wasSatisfied = self.lastPathSatisfied
                let previousPrimary = self.lastPrimaryInterface
                self.lastPathSatisfied = isSatisfied
                self.lastPrimaryInterface = primary

                // If the network just came back AND we're in the middle of
                // a reconnect backoff, jump the queue and retry now.
                if !wasSatisfied, isSatisfied, case .reconnecting = self.state {
                    self.reconnectTask?.cancel()
                    self.kickReconnect(immediate: true)
                    return
                }

                // The interface switched (WiFi ↔ cellular ↔ wired) while we
                // thought we were connected. The old socket is dead even
                // though it hasn't timed out yet — reconnect now so the user
                // doesn't stare at a frozen terminal. tmux re-attach lands
                // them exactly where they were.
                if isSatisfied, case .connected = self.state,
                   let previousPrimary, let primary, previousPrimary != primary {
                    self.forceReconnect()
                }
            }
        }
        pathMonitor.start(queue: monitorQueue)
    }

    /// The interface a path is primarily using, in priority order. Pure, so
    /// it's safe to call from the nonisolated path-monitor callback.
    private nonisolated static func primaryInterface(of path: NWPath) -> NWInterface.InterfaceType? {
        for type in [NWInterface.InterfaceType.wifi, .wiredEthernet, .cellular] where path.usesInterfaceType(type) {
            return type
        }
        return path.availableInterfaces.first?.type
    }

    /// Tear down the current (now-dead) client and reconnect immediately,
    /// surfaced as a reconnect so the screen stays put and tmux re-attaches.
    private func forceReconnect() {
        guard !userInitiatedStop else { return }
        reconnectAttempt = 0
        reconnectTask?.cancel()
        let stale = client
        client = nil
        Task { await stale?.disconnect() }
        state = .reconnecting
        kickReconnect(immediate: true)
    }

    /// Called when the app returns to the foreground. iOS suspends us in the
    /// background and kills sockets, so a session that knows it's down (or was
    /// mid-backoff when we got frozen) should retry instantly rather than
    /// leave the user on a stale screen or the disconnected overlay.
    func reconnectIfNeeded() {
        guard !userInitiatedStop else { return }
        switch state {
        case .connecting:
            return
        case .connected:
            // After a suspension, state can still say .connected while iOS
            // already killed the socket — verify the transport and recover
            // instead of leaving the user on a dead screen.
            if client?.isTransportActive != true {
                forceReconnect()
            }
        case .idle, .reconnecting, .disconnected:
            reconnectAttempt = 0
            reconnectTask?.cancel()
            state = .reconnecting
            kickReconnect(immediate: true)
        }
    }

    // MARK: - Lifecycle

    func start() async {
        userInitiatedStop = false
        reconnectAttempt = 0
        reconnectTask?.cancel()
        reconnectTask = nil
        await connectOnce(isReconnect: false)
    }

    /// One connect attempt. On success, transitions to `.connected`. On
    /// failure, leaves state at `.disconnected` (caller decides whether
    /// to retry).
    private func connectOnce(isReconnect: Bool) async {
        state = isReconnect ? .reconnecting : .connecting
        tmuxFallbackTriggered = false
        hostKeyConflict = false

        let client = SSHClient(configuration: configuration)
        client.onOutput = { [weak self] data in
            // `DispatchQueue.main.async` is strictly FIFO, so output chunks
            // render in arrival order — separately-created `Task`s are not
            // order-guaranteed and could interleave under heavy output.
            DispatchQueue.main.async {
                MainActor.assumeIsolated {
                guard let self else { return }
                // In control mode the wire carries the protocol, not a screen.
                // Writing it straight to the renderer would paint "%output %3
                // …" as literal text.
                if let control = self.control {
                    // Until tmux has answered, keep a copy: if the handshake
                    // never lands, these bytes are a plain shell's output and
                    // are the only thing the user has.
                    if !control.isSynced { self.controlWarmup += [UInt8](data) }
                    control.receive([UInt8](data))
                    return
                }
                self.terminal.write(data)
                let str = String(data: data, encoding: .utf8)
                if self.persistenceMode == .tmuxAutoResume, !self.tmuxFallbackTriggered,
                   let str, TmuxResume.looksLikeTmuxMissing(str) {
                    self.tmuxFallbackTriggered = true
                    let hint = [
                        "\r\n\u{1B}[33m[shio] tmux not found — running plain shell.\u{1B}[0m",
                        "\u{1B}[2m       Install on this Mac with: \u{1B}[0m\u{1B}[1mbrew install tmux\u{1B}[0m",
                        "\u{1B}[2m       Once installed, your next connection will auto-resume.\u{1B}[0m\r\n",
                    ].joined(separator: "\r\n")
                    self.terminal.write(hint)
                }
                if let str { self.detectLatestURL(in: Self.stripANSI(str)) }
                }
            }
        }
        client.onDisconnect = { [weak self] error in
            Task { @MainActor [weak self] in
                guard let self else { return }
                guard !self.userInitiatedStop else {
                    self.state = .idle
                    return
                }
                self.handleUnexpectedDisconnect(reason: error?.localizedDescription)
            }
        }
        // Retire the previous client for real — when only the shell channel
        // died, its parent SSH/TCP connection would otherwise leak. Detach
        // the callbacks first so its teardown can't echo into this attempt.
        if let stale = self.client {
            stale.onOutput = nil
            stale.onDisconnect = nil
            Task { await stale.disconnect() }
        }
        self.client = client

        do {
            try await client.connect()
            // tmux sessions bootstrap via the SSH exec command, which runs in a
            // NON-interactive shell — bypassing .zshrc/.bashrc so a user's
            // auto-tmux can't preempt Shio's session. Fresh name, mouse on, and
            // status off all take effect; a new tab is reliably a fresh session.
            let useControl = persistenceMode == .tmuxAutoResume && TmuxControlSession.isEnabled
            let bootstrap: String?
            if useControl {
                bootstrap = TmuxResume.execLine(named: tmuxSessionName, startDir: startDirectory,
                                                cloneURL: cloneURL, controlMode: true)
                setUpControlMode(client: client)
            } else {
                control = nil
                renderedPaneID = nil
                bootstrap = persistenceMode == .tmuxAutoResume
                    ? TmuxResume.execLine(named: tmuxSessionName, startDir: startDirectory, cloneURL: cloneURL)
                    : nil
            }
            try await client.requestShell(command: bootstrap)
            // tmux is talking now. Find where its answers to Shio begin before
            // trusting any of them.
            if useControl {
                control?.start()
                startControlHandshakeWatchdog()
            }
            // The user may have closed the session while the connect was in
            // flight — don't resurrect it under them.
            if userInitiatedStop || Task.isCancelled {
                client.onOutput = nil
                client.onDisconnect = nil
                Task { await client.disconnect() }
                state = .idle
                return
            }
            state = .connected
            if !isReconnect {
                Haptics.notifySuccess()
                if let activeID = ownerSessionID {
                    LiveActivityController.shared.start(
                        sessionID: activeID,
                        hostName: hostName
                    )
                }
            } else {
                Haptics.light()
                if let activeID = ownerSessionID {
                    Task {
                        await LiveActivityController.shared.update(
                            sessionID: activeID,
                            connectionState: "connected"
                        )
                    }
                }
            }
            reconnectAttempt = 0
        } catch {
            // Connect itself failed.
            if userInitiatedStop {
                state = .idle
            } else if ReconnectPolicy.isPermanentFailure(error) {
                // Auth/key/host-key problems need the user, not a retry loop —
                // backing off ~31s would only bury the actionable error.
                if case SSHClient.SSHError.hostKeyChanged = error { hostKeyConflict = true }
                giveUp(reason: error.localizedDescription)
            } else {
                handleUnexpectedDisconnect(reason: error.localizedDescription, fromFailedRetry: true)
            }
        }
    }

    private func handleUnexpectedDisconnect(reason: String?, fromFailedRetry: Bool = false) {
        // A live shell dropping while a retry is already scheduled must not
        // pile on a duplicate task — but a *failed retry itself* (state is
        // .reconnecting by definition then) has to continue the chain, or
        // the loop dies after one attempt with a permanent spinner.
        if !fromFailedRetry, case .reconnecting = state { return }
        guard reconnectAttempt < ReconnectPolicy.maxAttempts else {
            giveUp(reason: reason)
            return
        }
        state = .reconnecting
        if let activeID = ownerSessionID {
            Task {
                await LiveActivityController.shared.update(
                    sessionID: activeID,
                    connectionState: "reconnecting"
                )
            }
        }
        kickReconnect(immediate: false)
    }

    /// Out of retries (or the failure is permanent): surface the disconnected
    /// overlay with the reason and wind down the Live Activity.
    private func giveUp(reason: String?) {
        state = .disconnected(reason: reason)
        Haptics.notifyError()
        // Two-stage cleanup of the Live Activity: update it once to
        // "disconnected" so the user sees that state briefly, then
        // schedule an explicit end so the activity disappears
        // rather than sitting on the lock screen indefinitely with
        // a stale claim. The 25s gap matches the
        // disconnectedStaleSeconds window so iOS would gray it out
        // around the same time anyway — but explicit end is more
        // honest than relying on iOS to do it.
        if let activeID = ownerSessionID {
            Task {
                await LiveActivityController.shared.update(
                    sessionID: activeID,
                    connectionState: "disconnected"
                )
                try? await Task.sleep(nanoseconds: 25_000_000_000)
                // The session may have reconnected during the grace window
                // (manual Retry, network back) — don't kill its live activity.
                guard case .disconnected = self.state else { return }
                await LiveActivityController.shared.end(
                    sessionID: activeID,
                    finalState: "disconnected"
                )
            }
        }
    }

    private func kickReconnect(immediate: Bool) {
        reconnectTask?.cancel()
        reconnectTask = Task { [weak self] in
            guard let self else { return }
            if !immediate {
                // Shared exponential backoff (0.5 → 16s). Task inherits
                // MainActor isolation here so reading `reconnectAttempt`
                // is synchronous.
                let delayMs = ReconnectPolicy.delayMilliseconds(forAttempt: self.reconnectAttempt)
                try? await Task.sleep(nanoseconds: delayMs * 1_000_000)
            }
            if Task.isCancelled { return }
            self.reconnectAttempt += 1
            await self.connectOnce(isReconnect: true)
        }
    }

    func stop() async {
        userInitiatedStop = true
        reconnectTask?.cancel()
        reconnectTask = nil
        resizeDebounce?.cancel()
        resizeDebounce = nil
        controlHandshake?.cancel()
        controlHandshake = nil
        control = nil
        renderedPaneID = nil
        controlWarmup = []
        await client?.disconnect()
        client = nil
        state = .idle
        terminal.shutdown()   // free the libghostty surface + release its +1 (else it leaks)
    }

    deinit {
        pathMonitor.cancel()
    }
}
