import Foundation
import SwiftUI
import Observation
import Network

/// Owns the live SSH session and its terminal surface. Bridges:
///
///   SSHClient  ─── onOutput ───→ LibGhosttyTerminalController.write
///   LibGhosttyTerminalController.onInput (terminal-generated bytes)
///   TerminalInputView.onBytes ─── write ───→ SSHClient.write
///   LibGhosttyTerminalController.onResize ─── resize ───→ SSHClient.resize
///
/// Also owns the auto-reconnect state machine: an unexpected SSH drop
/// (network blip, server restart, sleeping Mac waking, etc.) triggers
/// an exponential-backoff retry loop. A path monitor reacts immediately
/// to network re-availability so the user gets back to live as soon as
/// the radio comes back. tmux on the remote preserves the session, so
/// a successful reconnect lands the user exactly where they left off.
@Observable
@MainActor
final class SessionViewModel {

    enum ConnectionState: Equatable {
        case idle
        case connecting
        case connected
        case reconnecting
        case disconnected(reason: String?)
    }

    let terminal: LibGhosttyTerminalController
    private(set) var state: ConnectionState = .idle
    private(set) var hostName: String
    /// Multi-session index: 0 = primary tmux session, 1+ = additional
    /// concurrent sessions on the same host. Drives the tmux session name
    /// so they don't collide.
    let sessionIndex: Int
    var targetPort: Int { configuration.port }

    private var client: SSHClient?
    private var configuration: SSHClient.Configuration
    private let persistenceMode: Host.PersistenceMode
    private var tmuxFallbackTriggered = false

    // MARK: Reconnect state

    /// True once the user (or the parent view's onDisappear) explicitly
    /// closed the session. Suppresses auto-reconnect so we don't fight
    /// the user trying to leave.
    private var userInitiatedStop = false
    /// Current reconnect attempt count. Reset on a successful connect.
    private var reconnectAttempt = 0
    /// Task running the backoff loop. Cancellable so a path-change can
    /// short-circuit the wait.
    private var reconnectTask: Task<Void, Never>?
    /// Maximum reconnects before we give up and surface the disconnect
    /// overlay. Six attempts ~= 31s of exponential backoff, plenty of
    /// time for a brief tunnel/network flap to recover.
    private let maxReconnects = 6

    // MARK: Network monitor

    /// Watches for path changes (WiFi → cellular, network return, etc.)
    /// so we can react to connectivity events rather than just polling
    /// via the backoff.
    private let pathMonitor = NWPathMonitor()
    private let monitorQueue = DispatchQueue(label: "sh.shio.session.path")
    private var lastPathSatisfied: Bool = true

    init(
        configuration: SSHClient.Configuration,
        persistenceMode: Host.PersistenceMode = .tmuxAutoResume,
        sessionIndex: Int = 0
    ) {
        self.configuration = configuration
        self.hostName = configuration.host
        self.persistenceMode = persistenceMode
        self.sessionIndex = sessionIndex
        self.terminal = LibGhosttyTerminalController()
        wire()
        startPathMonitor()
    }

    private func wire() {
        terminal.onInput = { [weak self] data in
            self?.client?.write(data)
        }
        terminal.onResize = { [weak self] cols, rows in
            self?.client?.resize(cols: cols, rows: rows)
        }
        terminal.onLoadFailure = { [weak self] message in
            self?.state = .disconnected(reason: message)
        }
    }

    private func startPathMonitor() {
        pathMonitor.pathUpdateHandler = { [weak self] path in
            let isSatisfied = (path.status == .satisfied)
            Task { @MainActor [weak self] in
                guard let self else { return }
                let wasSatisfied = self.lastPathSatisfied
                self.lastPathSatisfied = isSatisfied
                // If the network just came back AND we're in the middle of
                // a reconnect backoff, jump the queue and retry now.
                if !wasSatisfied, isSatisfied, case .reconnecting = self.state {
                    self.reconnectTask?.cancel()
                    self.kickReconnect(immediate: true)
                }
            }
        }
        pathMonitor.start(queue: monitorQueue)
    }

    // MARK: - Lifecycle

    func start() async {
        userInitiatedStop = false
        reconnectAttempt = 0
        reconnectTask?.cancel()
        reconnectTask = nil
        await connectOnce(isReconnect: false)
    }

    /// One connect attempt. On success, transitions to `.connected`. On
    /// failure, leaves state at `.disconnected` (caller decides whether
    /// to retry).
    private func connectOnce(isReconnect: Bool) async {
        state = isReconnect ? .reconnecting : .connecting
        tmuxFallbackTriggered = false

        let client = SSHClient(configuration: configuration)
        client.onOutput = { [weak self] data in
            Task { @MainActor [weak self] in
                guard let self else { return }
                self.terminal.write(data)
                if self.persistenceMode == .tmuxAutoResume, !self.tmuxFallbackTriggered,
                   let str = String(data: data, encoding: .utf8),
                   TmuxResume.looksLikeTmuxMissing(str) {
                    self.tmuxFallbackTriggered = true
                    let hint = [
                        "\r\n\u{1B}[33m[shio] tmux not found — running plain shell.\u{1B}[0m",
                        "\u{1B}[2m       Install on this Mac with: \u{1B}[0m\u{1B}[1mbrew install tmux\u{1B}[0m",
                        "\u{1B}[2m       Once installed, your next connection will auto-resume.\u{1B}[0m\r\n",
                    ].joined(separator: "\r\n")
                    self.terminal.write(hint)
                }
            }
        }
        client.onDisconnect = { [weak self] error in
            Task { @MainActor [weak self] in
                guard let self else { return }
                guard !self.userInitiatedStop else {
                    self.state = .idle
                    return
                }
                self.handleUnexpectedDisconnect(reason: error?.localizedDescription)
            }
        }
        self.client = client

        do {
            try await client.connect()
            try await client.requestShell()
            state = .connected
            if !isReconnect {
                Haptics.notifySuccess()
                if let activeID = SessionStore.shared.activeSession?.id {
                    LiveActivityController.shared.start(
                        sessionID: activeID,
                        hostName: hostName
                    )
                }
            } else {
                Haptics.light()
                if let activeID = SessionStore.shared.activeSession?.id {
                    Task {
                        await LiveActivityController.shared.update(
                            sessionID: activeID,
                            connectionState: "connected"
                        )
                    }
                }
            }
            reconnectAttempt = 0
            if persistenceMode == .tmuxAutoResume {
                client.write(TmuxResume.resumeCommand(for: hostName, index: sessionIndex))
            }
        } catch {
            // Connect itself failed. Either kick the backoff (if a retry
            // is still in our budget) or surface the error.
            if !userInitiatedStop, reconnectAttempt < maxReconnects {
                handleUnexpectedDisconnect(reason: error.localizedDescription)
            } else {
                state = .disconnected(reason: error.localizedDescription)
            }
        }
    }

    private func handleUnexpectedDisconnect(reason: String?) {
        // Already retrying? Don't pile on a duplicate task.
        if case .reconnecting = state { return }
        guard reconnectAttempt < maxReconnects else {
            state = .disconnected(reason: reason)
            Haptics.notifyError()
            // Two-stage cleanup of the Live Activity: update it once to
            // "disconnected" so the user sees that state briefly, then
            // schedule an explicit end so the activity disappears
            // rather than sitting on the lock screen indefinitely with
            // a stale claim. The 25s gap matches the
            // disconnectedStaleSeconds window so iOS would gray it out
            // around the same time anyway — but explicit end is more
            // honest than relying on iOS to do it.
            if let activeID = SessionStore.shared.activeSession?.id {
                Task {
                    await LiveActivityController.shared.update(
                        sessionID: activeID,
                        connectionState: "disconnected"
                    )
                    try? await Task.sleep(nanoseconds: 25_000_000_000)
                    await LiveActivityController.shared.end(
                        sessionID: activeID,
                        finalState: "disconnected"
                    )
                }
            }
            return
        }
        state = .reconnecting
        if let activeID = SessionStore.shared.activeSession?.id {
            Task {
                await LiveActivityController.shared.update(
                    sessionID: activeID,
                    connectionState: "reconnecting"
                )
            }
        }
        kickReconnect(immediate: false)
    }

    private func kickReconnect(immediate: Bool) {
        reconnectTask?.cancel()
        reconnectTask = Task { [weak self] in
            guard let self else { return }
            if !immediate {
                // Exponential backoff: 0.5, 1, 2, 4, 8, 16 seconds. Capped
                // by maxReconnects so the worst case is ~31s of trying.
                // Task inherits MainActor isolation here so reading
                // `reconnectAttempt` is synchronous.
                let attempt = self.reconnectAttempt
                let delayMs = UInt64(500 * (1 << min(attempt, 5)))
                try? await Task.sleep(nanoseconds: delayMs * 1_000_000)
            }
            if Task.isCancelled { return }
            self.reconnectAttempt += 1
            await self.connectOnce(isReconnect: true)
        }
    }

    func stop() async {
        userInitiatedStop = true
        reconnectTask?.cancel()
        reconnectTask = nil
        await client?.disconnect()
        client = nil
        state = .idle
    }

    deinit {
        pathMonitor.cancel()
    }
}
