import Foundation
import SwiftUI
import Observation
import Network

/// Owns the live SSH session and its terminal surface. Bridges:
///
///   SSHClient  ─── onOutput ───→ LibGhosttyTerminalController.write
///   LibGhosttyTerminalController.onInput (terminal-generated bytes)
///   TerminalInputView.onBytes ─── write ───→ SSHClient.write
///   LibGhosttyTerminalController.onResize ─── resize ───→ SSHClient.resize
///
/// Also owns the auto-reconnect state machine: an unexpected SSH drop
/// (network blip, server restart, sleeping Mac waking, etc.) triggers
/// an exponential-backoff retry loop. A path monitor reacts immediately
/// to network re-availability so the user gets back to live as soon as
/// the radio comes back. tmux on the remote preserves the session, so
/// a successful reconnect lands the user exactly where they left off.
@Observable
@MainActor
final class SessionViewModel {

    enum ConnectionState: Equatable {
        case idle
        case connecting
        case connected
        case reconnecting
        case disconnected(reason: String?)
    }

    let terminal: LibGhosttyTerminalController
    private(set) var state: ConnectionState = .idle
    private(set) var hostName: String
    /// Multi-session index: 0 = primary tmux session, 1+ = additional
    /// concurrent sessions on the same host. Drives the tmux session name
    /// so they don't collide.
    let sessionIndex: Int
    /// Explicit tmux session name, e.g. `shio-<project>` or `shio-<host>`.
    let tmuxSessionName: String
    /// Directory to open the session in (the repo path for a project
    /// session), or nil to start in the login shell's default.
    let startDirectory: String?
    /// For projects created from a git URL: the URL to clone into
    /// `startDirectory` on first open (guarded — only if it doesn't exist).
    let cloneURL: String?
    var targetPort: Int { configuration.port }

    private var client: SSHClient?
    private var configuration: SSHClient.Configuration
    private let persistenceMode: Host.PersistenceMode
    private var tmuxFallbackTriggered = false

    // MARK: Resize debounce
    /// Latest grid size waiting to be pushed to the remote PTY.
    private var pendingResize: (cols: Int, rows: Int)?
    /// Coalesces the burst of resize callbacks that fire during rotation,
    /// split-view drags, and keyboard show/hide. libghostty re-renders
    /// locally on every change immediately; we only debounce the SIGWINCH to
    /// the remote so the shell/TUI isn't thrashed mid-animation.
    private var resizeDebounce: Task<Void, Never>?

    // MARK: Agent detection
    /// Set by `SessionStore` so output-watching can key `AgentStateStore` by
    /// the owning session's id (same id the Live Activity uses).
    var ownerSessionID: UUID?
    /// Rolling, ANSI-stripped tail of recent output fed to the classifier.
    private var agentTail = ""
    /// Last activity we pushed, so we only update on transitions.
    private var lastAgentActivity: AgentActivity = .none

    // MARK: Link detection
    /// The most recent http(s) URL seen in output, surfaced so the user can
    /// open it in an in-app browser — chiefly for CLIs (Claude Code login,
    /// `gh auth`, etc.) that would otherwise open a browser on the remote
    /// machine you can't reach from your phone. Cleared by the UI once used.
    private(set) var detectedURL: URL?
    private static let urlRegex = try? NSRegularExpression(
        pattern: "https?://[^\\s\"'<>)\\]}]+", options: [])

    // MARK: Reconnect state

    /// True once the user (or the parent view's onDisappear) explicitly
    /// closed the session. Suppresses auto-reconnect so we don't fight
    /// the user trying to leave.
    private var userInitiatedStop = false
    /// Current reconnect attempt count. Reset on a successful connect.
    private var reconnectAttempt = 0
    /// Task running the backoff loop. Cancellable so a path-change can
    /// short-circuit the wait.
    private var reconnectTask: Task<Void, Never>?
    /// Maximum reconnects before we give up and surface the disconnect
    /// overlay. Six attempts ~= 31s of exponential backoff, plenty of
    /// time for a brief tunnel/network flap to recover.
    private let maxReconnects = 6

    // MARK: Network monitor

    /// Watches for path changes (WiFi → cellular, network return, etc.)
    /// so we can react to connectivity events rather than just polling
    /// via the backoff.
    private let pathMonitor = NWPathMonitor()
    private let monitorQueue = DispatchQueue(label: "sh.shio.session.path")
    private var lastPathSatisfied: Bool = true
    /// The interface the connection was last riding (WiFi / cellular / wired).
    /// A change while we believe we're connected means the old socket is dead,
    /// so we reconnect immediately instead of waiting for the TCP timeout.
    private var lastPrimaryInterface: NWInterface.InterfaceType?

    init(
        configuration: SSHClient.Configuration,
        persistenceMode: Host.PersistenceMode = .tmuxAutoResume,
        sessionIndex: Int = 0,
        tmuxSessionName: String? = nil,
        startDirectory: String? = nil,
        cloneURL: String? = nil
    ) {
        self.configuration = configuration
        self.hostName = configuration.host
        self.persistenceMode = persistenceMode
        self.sessionIndex = sessionIndex
        self.tmuxSessionName = tmuxSessionName
            ?? TmuxResume.sessionName(for: configuration.host, index: sessionIndex)
        self.startDirectory = startDirectory
        self.cloneURL = cloneURL
        self.terminal = LibGhosttyTerminalController()
        wire()
        startPathMonitor()
    }

    private func wire() {
        terminal.onInput = { [weak self] data in
            self?.client?.write(data)
        }
        terminal.onResize = { [weak self] cols, rows in
            self?.scheduleResize(cols: cols, rows: rows)
        }
        terminal.onLoadFailure = { [weak self] message in
            self?.state = .disconnected(reason: message)
        }
    }

    /// Feed a chunk of raw output into the output-watching agent classifier,
    /// update the shared `AgentStateStore`, and surface activity transitions
    /// (especially → waiting) on the Live Activity.
    private func ingestForAgentDetection(_ raw: String) {
        guard let id = ownerSessionID else { return }
        let cleaned = AgentDetector.strip(raw)
        agentTail += cleaned
        if agentTail.count > 4000 { agentTail = String(agentTail.suffix(4000)) }

        detectLatestURL(in: cleaned)

        let snapshot = AgentDetector.classify(cleanTail: agentTail)
        AgentStateStore.shared.update(sessionID: id, snapshot)

        guard snapshot.activity != lastAgentActivity else { return }
        lastAgentActivity = snapshot.activity
        if case .connected = state {
            Task {
                await LiveActivityController.shared.update(
                    sessionID: id,
                    connectionState: "connected",
                    agentName: snapshot.agentName,
                    agentActivity: snapshot.activity == .none ? nil : snapshot.activity.rawValue
                )
            }
        }
    }

    /// Scan a freshly arrived (ANSI-stripped) chunk for an http(s) URL and
    /// surface the last one found. Trailing punctuation is trimmed so a URL
    /// printed at the end of a sentence still opens cleanly.
    private func detectLatestURL(in chunk: String) {
        guard let regex = Self.urlRegex else { return }
        let range = NSRange(chunk.startIndex..., in: chunk)
        let matches = regex.matches(in: chunk, range: range)
        guard let last = matches.last, let r = Range(last.range, in: chunk) else { return }
        var candidate = String(chunk[r])
        while let trailing = candidate.last, ".,;:".contains(trailing) { candidate.removeLast() }
        if let url = URL(string: candidate), url != detectedURL {
            detectedURL = url
        }
    }

    /// Called by the UI after opening (or dismissing) the surfaced link.
    func clearDetectedURL() { detectedURL = nil }

    /// If `url` is an OAuth link whose redirect targets the host's loopback
    /// (`localhost:PORT`), open an SSH local forward for that port so the
    /// in-app browser's redirect tunnels back to the host's callback server
    /// and the login completes. Returns the forward to keep alive until the
    /// browser closes, or nil when no forward is needed/possible.
    func prepareLoopbackForward(for url: URL) async -> SSHPortForward? {
        guard case .connected = state, let client else { return nil }
        guard let port = Self.loopbackRedirectPort(in: url) else { return nil }
        return try? await client.openLocalForward(localPort: port, remotePort: port)
    }

    /// Pull a loopback callback port out of an auth URL — from a
    /// `redirect_uri`/`callback` query item, or the URL itself if it's a
    /// localhost link.
    private static func loopbackRedirectPort(in url: URL) -> Int? {
        if isLoopbackHost(url.host), let port = url.port { return port }

        guard let comps = URLComponents(url: url, resolvingAgainstBaseURL: false),
              let items = comps.queryItems else { return nil }
        let keys = ["redirect_uri", "redirect", "callback", "callback_url", "return_to"]
        for item in items where keys.contains(item.name.lowercased()) {
            guard let raw = item.value else { continue }
            let decoded = raw.removingPercentEncoding ?? raw
            if let inner = URLComponents(string: decoded), isLoopbackHost(inner.host), let port = inner.port {
                return port
            }
        }
        return nil
    }

    private static func isLoopbackHost(_ host: String?) -> Bool {
        host == "localhost" || host == "127.0.0.1" || host == "[::1]" || host == "::1"
    }

    /// Debounce remote PTY resizes (~120ms trailing). The last size in a
    /// burst wins, so a rotation that sweeps through intermediate grid sizes
    /// sends a single window-change to the remote.
    private func scheduleResize(cols: Int, rows: Int) {
        pendingResize = (cols, rows)
        resizeDebounce?.cancel()
        resizeDebounce = Task { [weak self] in
            try? await Task.sleep(nanoseconds: 120_000_000)
            guard let self, !Task.isCancelled, let size = self.pendingResize else { return }
            self.client?.resize(cols: size.cols, rows: size.rows)
            self.pendingResize = nil
        }
    }

    private func startPathMonitor() {
        pathMonitor.pathUpdateHandler = { [weak self] path in
            let isSatisfied = (path.status == .satisfied)
            let primary = SessionViewModel.primaryInterface(of: path)
            Task { @MainActor [weak self] in
                guard let self else { return }
                let wasSatisfied = self.lastPathSatisfied
                let previousPrimary = self.lastPrimaryInterface
                self.lastPathSatisfied = isSatisfied
                self.lastPrimaryInterface = primary

                // If the network just came back AND we're in the middle of
                // a reconnect backoff, jump the queue and retry now.
                if !wasSatisfied, isSatisfied, case .reconnecting = self.state {
                    self.reconnectTask?.cancel()
                    self.kickReconnect(immediate: true)
                    return
                }

                // The interface switched (WiFi ↔ cellular ↔ wired) while we
                // thought we were connected. The old socket is dead even
                // though it hasn't timed out yet — reconnect now so the user
                // doesn't stare at a frozen terminal. tmux re-attach lands
                // them exactly where they were.
                if isSatisfied, case .connected = self.state,
                   let previousPrimary, let primary, previousPrimary != primary {
                    self.forceReconnect()
                }
            }
        }
        pathMonitor.start(queue: monitorQueue)
    }

    /// The interface a path is primarily using, in priority order. Pure, so
    /// it's safe to call from the nonisolated path-monitor callback.
    private nonisolated static func primaryInterface(of path: NWPath) -> NWInterface.InterfaceType? {
        for type in [NWInterface.InterfaceType.wifi, .wiredEthernet, .cellular] where path.usesInterfaceType(type) {
            return type
        }
        return path.availableInterfaces.first?.type
    }

    /// Tear down the current (now-dead) client and reconnect immediately,
    /// surfaced as a reconnect so the screen stays put and tmux re-attaches.
    private func forceReconnect() {
        guard !userInitiatedStop else { return }
        reconnectAttempt = 0
        reconnectTask?.cancel()
        let stale = client
        client = nil
        Task { await stale?.disconnect() }
        state = .reconnecting
        kickReconnect(immediate: true)
    }

    /// Called when the app returns to the foreground. iOS suspends us in the
    /// background and kills sockets, so a session that knows it's down (or was
    /// mid-backoff when we got frozen) should retry instantly rather than
    /// leave the user on a stale screen or the disconnected overlay.
    func reconnectIfNeeded() {
        guard !userInitiatedStop else { return }
        switch state {
        case .connected, .connecting:
            return
        case .idle, .reconnecting, .disconnected:
            reconnectAttempt = 0
            reconnectTask?.cancel()
            state = .reconnecting
            kickReconnect(immediate: true)
        }
    }

    // MARK: - Lifecycle

    func start() async {
        userInitiatedStop = false
        reconnectAttempt = 0
        reconnectTask?.cancel()
        reconnectTask = nil
        await connectOnce(isReconnect: false)
    }

    /// One connect attempt. On success, transitions to `.connected`. On
    /// failure, leaves state at `.disconnected` (caller decides whether
    /// to retry).
    private func connectOnce(isReconnect: Bool) async {
        state = isReconnect ? .reconnecting : .connecting
        tmuxFallbackTriggered = false

        let client = SSHClient(configuration: configuration)
        client.onOutput = { [weak self] data in
            // `DispatchQueue.main.async` is strictly FIFO, so output chunks
            // render in arrival order — separately-created `Task`s are not
            // order-guaranteed and could interleave under heavy output.
            DispatchQueue.main.async {
                MainActor.assumeIsolated {
                guard let self else { return }
                self.terminal.write(data)
                let str = String(data: data, encoding: .utf8)
                if self.persistenceMode == .tmuxAutoResume, !self.tmuxFallbackTriggered,
                   let str, TmuxResume.looksLikeTmuxMissing(str) {
                    self.tmuxFallbackTriggered = true
                    let hint = [
                        "\r\n\u{1B}[33m[shio] tmux not found — running plain shell.\u{1B}[0m",
                        "\u{1B}[2m       Install on this Mac with: \u{1B}[0m\u{1B}[1mbrew install tmux\u{1B}[0m",
                        "\u{1B}[2m       Once installed, your next connection will auto-resume.\u{1B}[0m\r\n",
                    ].joined(separator: "\r\n")
                    self.terminal.write(hint)
                }
                if let str { self.ingestForAgentDetection(str) }
                }
            }
        }
        client.onDisconnect = { [weak self] error in
            Task { @MainActor [weak self] in
                guard let self else { return }
                guard !self.userInitiatedStop else {
                    self.state = .idle
                    return
                }
                self.handleUnexpectedDisconnect(reason: error?.localizedDescription)
            }
        }
        self.client = client

        do {
            try await client.connect()
            try await client.requestShell()
            state = .connected
            if !isReconnect {
                Haptics.notifySuccess()
                if let activeID = ownerSessionID {
                    LiveActivityController.shared.start(
                        sessionID: activeID,
                        hostName: hostName
                    )
                }
            } else {
                Haptics.light()
                if let activeID = ownerSessionID {
                    Task {
                        await LiveActivityController.shared.update(
                            sessionID: activeID,
                            connectionState: "connected"
                        )
                    }
                }
            }
            reconnectAttempt = 0
            if persistenceMode == .tmuxAutoResume {
                client.write(TmuxResume.resumeCommand(named: tmuxSessionName, startDir: startDirectory, cloneURL: cloneURL))
            }
        } catch {
            // Connect itself failed. Either kick the backoff (if a retry
            // is still in our budget) or surface the error.
            if !userInitiatedStop, reconnectAttempt < maxReconnects {
                handleUnexpectedDisconnect(reason: error.localizedDescription)
            } else {
                state = .disconnected(reason: error.localizedDescription)
            }
        }
    }

    private func handleUnexpectedDisconnect(reason: String?) {
        // Already retrying? Don't pile on a duplicate task.
        if case .reconnecting = state { return }
        guard reconnectAttempt < maxReconnects else {
            state = .disconnected(reason: reason)
            Haptics.notifyError()
            // Two-stage cleanup of the Live Activity: update it once to
            // "disconnected" so the user sees that state briefly, then
            // schedule an explicit end so the activity disappears
            // rather than sitting on the lock screen indefinitely with
            // a stale claim. The 25s gap matches the
            // disconnectedStaleSeconds window so iOS would gray it out
            // around the same time anyway — but explicit end is more
            // honest than relying on iOS to do it.
            if let activeID = ownerSessionID {
                Task {
                    await LiveActivityController.shared.update(
                        sessionID: activeID,
                        connectionState: "disconnected"
                    )
                    try? await Task.sleep(nanoseconds: 25_000_000_000)
                    await LiveActivityController.shared.end(
                        sessionID: activeID,
                        finalState: "disconnected"
                    )
                }
            }
            return
        }
        state = .reconnecting
        if let activeID = ownerSessionID {
            Task {
                await LiveActivityController.shared.update(
                    sessionID: activeID,
                    connectionState: "reconnecting"
                )
            }
        }
        kickReconnect(immediate: false)
    }

    private func kickReconnect(immediate: Bool) {
        reconnectTask?.cancel()
        reconnectTask = Task { [weak self] in
            guard let self else { return }
            if !immediate {
                // Exponential backoff: 0.5, 1, 2, 4, 8, 16 seconds. Capped
                // by maxReconnects so the worst case is ~31s of trying.
                // Task inherits MainActor isolation here so reading
                // `reconnectAttempt` is synchronous.
                let attempt = self.reconnectAttempt
                let delayMs = UInt64(500 * (1 << min(attempt, 5)))
                try? await Task.sleep(nanoseconds: delayMs * 1_000_000)
            }
            if Task.isCancelled { return }
            self.reconnectAttempt += 1
            await self.connectOnce(isReconnect: true)
        }
    }

    func stop() async {
        userInitiatedStop = true
        reconnectTask?.cancel()
        reconnectTask = nil
        resizeDebounce?.cancel()
        resizeDebounce = nil
        await client?.disconnect()
        client = nil
        state = .idle
        terminal.shutdown()   // free the libghostty surface + release its +1 (else it leaks)
    }

    deinit {
        pathMonitor.cancel()
    }
}
