import AppKit
import GhosttyKit

/// Native macOS host for a libghostty terminal surface, backed by a Metal
/// layer. Unlike the iOS surface (which uses the EXTERNAL IO backend and is
/// fed SSH bytes), this uses the DEFAULT backend so libghostty forks/execs a
/// real local shell and owns the PTY — a true local terminal.
///
/// M2 scaffold: local shell, rendering, keyboard, scroll, focus, resize.
/// Invisible-tmux wrapping (for continuity), tabs/splits, and SSH sessions
/// layer on in later milestones. Visual render + input feel need on-device
/// verification (can't be validated by a headless build).
final class GhosttyMacSurface: NSView, NSUserInterfaceValidations {

    /// How the surface gets its bytes.
    ///   - `.local`: libghostty forks/execs a shell and owns the PTY (DEFAULT).
    ///   - `.external`: the embedder feeds bytes via `writeBytes` and receives
    ///     terminal output through `onOutput` — the SSH path, identical to iOS.
    enum Backend { case local, external }

    /// LOCAL backend launch override. When nil, libghostty forks/execs a plain
    /// login shell (the "perfect plain shell" — the default Terminal tab).
    /// When set, ghostty execs `command` in `workingDirectory` with `env`
    /// applied — used to open a Project inside an invisible-tmux session while
    /// staying graceful if tmux is absent. See `MacLocalLaunch`.
    struct LocalLaunch {
        var workingDirectory: String?
        var command: String?
        var env: [String: String] = [:]
    }

    /// Called when this surface becomes first responder (click / tab focus) —
    /// lets the split tree track which pane is focused.
    var onFocus: (() -> Void)?

    /// EXTERNAL backend: terminal-generated bytes (user input, OSC) to send
    /// upstream (i.e. to SSH).
    var onOutput: ((Data) -> Void)?
    /// EXTERNAL backend: the grid resized — forward a window-change upstream.
    var onResize: ((_ cols: UInt16, _ rows: UInt16) -> Void)?

    nonisolated(unsafe) private var surface: ghostty_surface_t?
    nonisolated(unsafe) private var userdataRetained: Unmanaged<GhosttyMacSurface>?
    private let backend: Backend
    private let launch: LocalLaunch?
    private var fontSize: Float = Float(MacSettings.fontSize)

    /// The command ghostty execs for a plain local tab: the user's configured
    /// shell, else their login shell (`$SHELL` / passwd), falling back to zsh.
    private static var loginShellCommand: String { MacSettings.defaultShell }

    init(backend: Backend = .local, launch: LocalLaunch? = nil, frame frameRect: NSRect = .zero) {
        self.backend = backend
        self.launch = launch
        super.init(frame: frameRect.isEmpty ? NSRect(x: 0, y: 0, width: 800, height: 500) : frameRect)
        wantsLayer = true
        commonInit()
    }
    required init?(coder: NSCoder) { self.backend = .local; self.launch = nil; super.init(coder: coder); wantsLayer = true; commonInit() }

    deinit {
        if let surface { ghostty_surface_free(surface) }
        userdataRetained?.release()
    }

    /// Metal-backed layer (libghostty renders into a sublayer it owns).
    override func makeBackingLayer() -> CALayer { CAMetalLayer() }

    override var acceptsFirstResponder: Bool { true }
    override var isFlipped: Bool { true }

    private func commonInit() {
        LibGhosttyBridge.shared.ensureInitialized()
        guard let app = LibGhosttyBridge.shared.app else { return }

        let retained = Unmanaged.passRetained(self)
        userdataRetained = retained
        let userdata = retained.toOpaque()

        var cfg = ghostty_surface_config_new()
        cfg.userdata = userdata
        cfg.font_size = fontSize
        cfg.platform_tag = GHOSTTY_PLATFORM_MACOS
        cfg.platform = ghostty_platform_u(
            macos: ghostty_platform_macos_s(nsview: Unmanaged.passUnretained(self).toOpaque())
        )
        cfg.scale_factor = Double(window?.backingScaleFactor ?? 2.0)

        // Holds strdup'd C strings alive until after ghostty_surface_new (which
        // copies the config). Freed at the end of commonInit.
        var heap: [UnsafeMutablePointer<CChar>] = []
        func dup(_ s: String) -> UnsafePointer<CChar> {
            let p = strdup(s)!
            heap.append(p)
            return UnsafePointer(p)
        }
        var envVars: [ghostty_env_var_s] = []

        switch backend {
        case .local:
            // libghostty forks/execs and owns the PTY. With no launch override
            // this is a plain login shell; with one, it execs the Project's
            // invisible-tmux command in the repo directory.
            //
            // We ALWAYS hand ghostty an explicit `command`. The standalone
            // Ghostty.app resolves the user's default shell up in its app layer
            // (which an embedder like us doesn't run); the embedded libghostty
            // surface, given a nil command, no longer spawns a shell on its own
            // — the PTY child never execs, so the surface comes up as a bare
            // blinking cursor that ignores input. Passing the login shell
            // explicitly restores a working local terminal.
            cfg.io_backend = UInt8(GHOSTTY_IO_BACKEND_DEFAULT.rawValue)
            if let dir = launch?.workingDirectory { cfg.working_directory = dup(dir) }
            cfg.command = dup(launch?.command ?? Self.loginShellCommand)
            for (k, v) in launch?.env ?? [:] {
                envVars.append(ghostty_env_var_s(key: dup(k), value: dup(v)))
            }
        case .external:
            // The embedder owns IO: bytes in via writeBytes, output out via
            // onOutput — the SSH path, mirroring the iOS surface.
            cfg.io_backend = UInt8(GHOSTTY_IO_BACKEND_EXTERNAL.rawValue)
            cfg.io_userdata = userdata
            cfg.io_write_callback = { userdata, ptr, len in
                guard let userdata, let ptr, len > 0 else { return }
                let view = Unmanaged<GhosttyMacSurface>.fromOpaque(userdata).takeUnretainedValue()
                let data = Data(bytes: ptr, count: len)
                DispatchQueue.main.async { view.onOutput?(data) }
            }
            cfg.io_resize_callback = { userdata, cols, rows, _, _ in
                guard let userdata else { return }
                let view = Unmanaged<GhosttyMacSurface>.fromOpaque(userdata).takeUnretainedValue()
                DispatchQueue.main.async { view.onResize?(cols, rows) }
            }
        }

        envVars.withUnsafeMutableBufferPointer { buf in
            cfg.env_vars = buf.baseAddress
            cfg.env_var_count = buf.count
            if let surface = ghostty_surface_new(app, &cfg) {
                self.surface = surface
            }
        }
        heap.forEach { free($0) }
    }

    /// EXTERNAL backend: push bytes (SSH output) into the terminal display.
    func writeBytes(_ data: Data) {
        guard let surface else { return }
        data.withUnsafeBytes { (buf: UnsafeRawBufferPointer) in
            guard let base = buf.baseAddress else { return }
            ghostty_surface_write_bytes(surface, base.assumingMemoryBound(to: UInt8.self), UInt(buf.count))
        }
    }

    // MARK: Layout / sizing

    override func viewDidMoveToWindow() {
        super.viewDidMoveToWindow()
        updateSurfaceSize()
        // Grab the keyboard as soon as the surface is in its window — fixes
        // "had to click the terminal to start typing" on launch / new tab /
        // tab switch. Don't steal focus if another terminal already holds it
        // (e.g. the other pane of a split); PaneHost's focusedPaneID drives
        // that case.
        guard let window, !(window.firstResponder is GhosttyMacSurface) else { return }
        DispatchQueue.main.async { [weak self] in
            guard let self, self.window != nil else { return }
            self.window?.makeFirstResponder(self)
        }
    }

    override func layout() {
        super.layout()
        if let sublayers = layer?.sublayers {
            CATransaction.begin()
            CATransaction.setDisableActions(true)
            for sub in sublayers { sub.frame = bounds }
            CATransaction.commit()
        }
        updateSurfaceSize()
    }

    private func updateSurfaceSize() {
        guard let surface else { return }
        let scale = window?.backingScaleFactor ?? 2.0
        let w = bounds.width * scale
        let h = bounds.height * scale
        // Never hand ghostty a degenerate size. A split's HSplitView proposes a
        // transient 0×0 while it settles; set_size(0,0) makes the Metal renderer
        // spin trying to acquire a zero-size drawable → beachball.
        guard w >= 1, h >= 1 else { return }
        ghostty_surface_set_content_scale(surface, scale, scale)
        ghostty_surface_set_size(surface, UInt32(w), UInt32(h))
    }

    // MARK: Focus

    override func becomeFirstResponder() -> Bool {
        if let surface { ghostty_surface_set_focus(surface, true) }
        onFocus?()
        return super.becomeFirstResponder()
    }
    override func resignFirstResponder() -> Bool {
        if let surface { ghostty_surface_set_focus(surface, false) }
        return super.resignFirstResponder()
    }

    // MARK: Input

    override func keyDown(with event: NSEvent) {
        sendKey(event, action: event.isARepeat ? GHOSTTY_ACTION_REPEAT : GHOSTTY_ACTION_PRESS)
    }
    override func keyUp(with event: NSEvent) {
        sendKey(event, action: GHOSTTY_ACTION_RELEASE)
    }

    private func sendKey(_ event: NSEvent, action: ghostty_input_action_e) {
        guard let surface else { return }
        let chars = event.characters ?? ""
        let unshifted = event.charactersIgnoringModifiers?.unicodeScalars.first?.value ?? 0
        let flags = event.modifierFlags

        // Only forward `text` for genuine printable input. Control characters
        // (backspace 0x7F, return, tab…), the private-use codepoints AppKit
        // uses for function keys / arrows (0xF700–0xF8FF), and Ctrl/Cmd chords
        // must NOT be sent as text — ghostty would insert the raw character
        // (e.g. a literal DEL, breaking backspace). Those are encoded from
        // keycode + mods instead. Printable letters/digits/symbols still flow
        // through `text` so non-US layouts and symbol keys work.
        let nonText = chars.unicodeScalars.contains {
            $0.value < 0x20 || $0.value == 0x7F || (0xF700...0xF8FF).contains($0.value)
        }
        let suppressText = nonText || flags.contains(.control) || flags.contains(.command)
        let textToSend = suppressText ? "" : chars

        textToSend.withCString { cText in
            var key = ghostty_input_key_s()
            key.action = action
            key.mods = Self.mods(from: flags)
            key.consumed_mods = GHOSTTY_MODS_NONE
            // `keycode` is the RAW native macOS virtual keycode — libghostty
            // translates it to a logical key via the system keyboard layout
            // (the Carbon TIS APIs the macOS slice links). Passing a ghostty
            // GHOSTTY_KEY_* enum here instead is wrong: it breaks Enter,
            // Delete, arrows, and Ctrl-chords (text-producing keys still work
            // because they ride the `text` field).
            key.keycode = UInt32(event.keyCode)
            key.text = cText
            key.unshifted_codepoint = unshifted
            key.composing = false
            _ = ghostty_surface_key(surface, key)
        }
    }

    override func scrollWheel(with event: NSEvent) {
        guard let surface else { return }
        let precision: Int32 = event.hasPreciseScrollingDeltas ? 1 : 0
        ghostty_surface_mouse_scroll(surface, Double(event.scrollingDeltaX), Double(event.scrollingDeltaY), precision)
    }

    // MARK: Mouse — selection + hover

    /// A tracking area so libghostty sees mouse movement (cursor shape, link
    /// hover) while the surface is the active view.
    private var trackingArea: NSTrackingArea?
    override func updateTrackingAreas() {
        super.updateTrackingAreas()
        if let trackingArea { removeTrackingArea(trackingArea) }
        let area = NSTrackingArea(
            rect: bounds,
            options: [.mouseMoved, .activeInKeyWindow, .inVisibleRect],
            owner: self, userInfo: nil
        )
        addTrackingArea(area)
        trackingArea = area
    }

    /// Forward the cursor position in logical points. The view is `isFlipped`,
    /// so converted coordinates already have ghostty's top-left origin — no Y
    /// flip needed (unlike Ghostty's own bottom-left AppKit view).
    private func sendMousePos(_ event: NSEvent) {
        guard let surface else { return }
        let p = convert(event.locationInWindow, from: nil)
        ghostty_surface_mouse_pos(surface, Double(p.x), Double(p.y), Self.mods(from: event.modifierFlags))
    }

    override func mouseMoved(with event: NSEvent) { sendMousePos(event) }
    override func mouseDragged(with event: NSEvent) { sendMousePos(event) }
    override func rightMouseDragged(with event: NSEvent) { sendMousePos(event) }
    override func otherMouseDragged(with event: NSEvent) { sendMousePos(event) }

    override func mouseDown(with event: NSEvent) {
        window?.makeFirstResponder(self)
        sendMousePos(event)
        sendMouseButton(GHOSTTY_MOUSE_PRESS, .left, event)
    }
    override func mouseUp(with event: NSEvent) {
        sendMousePos(event)
        sendMouseButton(GHOSTTY_MOUSE_RELEASE, .left, event)
    }
    override func rightMouseDown(with event: NSEvent) {
        sendMousePos(event); sendMouseButton(GHOSTTY_MOUSE_PRESS, .right, event)
    }
    override func rightMouseUp(with event: NSEvent) {
        sendMousePos(event); sendMouseButton(GHOSTTY_MOUSE_RELEASE, .right, event)
    }

    private enum MouseButton { case left, right }
    private func sendMouseButton(_ state: ghostty_input_mouse_state_e, _ button: MouseButton, _ event: NSEvent) {
        guard let surface else { return }
        let b: ghostty_input_mouse_button_e = (button == .left) ? GHOSTTY_MOUSE_LEFT : GHOSTTY_MOUSE_RIGHT
        _ = ghostty_surface_mouse_button(surface, state, b, Self.mods(from: event.modifierFlags))
    }

    // MARK: Menu actions (dispatched to the focused surface via the responder
    // chain — see ShioMacApp's menu commands).

    /// Trigger a libghostty keybind action by name (e.g. "clear_screen",
    /// "increase_font_size:1", "scroll_page_up").
    func perform(_ action: String) {
        guard let surface else { return }
        action.withCString { _ = ghostty_surface_binding_action(surface, $0, UInt(strlen($0))) }
    }

    @objc func terminalIncreaseFontSize(_ sender: Any?) { perform("increase_font_size:1") }
    @objc func terminalDecreaseFontSize(_ sender: Any?) { perform("decrease_font_size:1") }
    @objc func terminalResetFontSize(_ sender: Any?)    { perform("reset_font_size") }
    @objc func terminalClearScreen(_ sender: Any?)      { perform("clear_screen") }
    @objc func terminalScrollPageUp(_ sender: Any?)     { perform("scroll_page_up") }
    @objc func terminalScrollPageDown(_ sender: Any?)   { perform("scroll_page_down") }
    @objc func terminalScrollToTop(_ sender: Any?)      { perform("scroll_to_top") }
    @objc func terminalScrollToBottom(_ sender: Any?)   { perform("scroll_to_bottom") }

    // Find-in-scrollback. The `search` binding action sets the needle and
    // ghostty's renderer highlights matches in the viewport itself (empty
    // needle cancels). `navigate_search` steps between matches. (NOTE:
    // `start_search` is intentionally a no-op in ghostty — it only pokes the
    // apprt to open a UI — so we drive `search:<text>` directly instead.)
    func searchSet(_ needle: String) { perform("search:\(needle)") }
    func searchNavigate(next: Bool)  { perform(next ? "navigate_search:next" : "navigate_search:previous") }
    func searchEnd()                 { perform("end_search") }

    /// Copy the current selection to the system pasteboard. The shared bridge
    /// stubs libghostty's clipboard ferrying (iOS handles the pasteboard
    /// directly), so we read the selection out and write NSPasteboard ourselves.
    @objc func copy(_ sender: Any?) {
        guard let surface, ghostty_surface_has_selection(surface) else { return }
        var text = ghostty_text_s()
        guard ghostty_surface_read_selection(surface, &text), let ptr = text.text else { return }
        let s = String(decoding: UnsafeRawBufferPointer(start: ptr, count: Int(text.text_len)), as: UTF8.self)
        ghostty_surface_free_text(surface, &text)
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(s, forType: .string)
    }

    /// Paste the pasteboard string by feeding it to the surface as typed text.
    @objc func paste(_ sender: Any?) {
        guard let surface, let s = NSPasteboard.general.string(forType: .string) else { return }
        s.withCString { ghostty_surface_text(surface, $0, UInt(strlen($0))) }
    }

    /// Enable Copy only when there's a selection; Paste only when the
    /// pasteboard has a string. Keeps the standard Edit menu honest.
    func validateUserInterfaceItem(_ item: any NSValidatedUserInterfaceItem) -> Bool {
        switch item.action {
        case #selector(copy(_:)):
            return surface.map { ghostty_surface_has_selection($0) } ?? false
        case #selector(paste(_:)):
            return NSPasteboard.general.string(forType: .string) != nil
        default:
            return true
        }
    }

    // MARK: NSEvent → ghostty translation

    private static func mods(from flags: NSEvent.ModifierFlags) -> ghostty_input_mods_e {
        var m: UInt32 = GHOSTTY_MODS_NONE.rawValue
        if flags.contains(.shift)   { m |= GHOSTTY_MODS_SHIFT.rawValue }
        if flags.contains(.control) { m |= GHOSTTY_MODS_CTRL.rawValue }
        if flags.contains(.option)  { m |= GHOSTTY_MODS_ALT.rawValue }
        if flags.contains(.command) { m |= GHOSTTY_MODS_SUPER.rawValue }
        if flags.contains(.capsLock){ m |= GHOSTTY_MODS_CAPS.rawValue }
        return ghostty_input_mods_e(m)
    }
}

// MARK: - SwiftUI host

import SwiftUI

/// Embeds a `GhosttyMacSurface` in SwiftUI and makes it first responder so
/// keystrokes flow to the terminal.
struct GhosttyMacTerminal: NSViewRepresentable {
    func makeNSView(context: Context) -> GhosttyMacSurface {
        let view = GhosttyMacSurface(frame: .zero)
        DispatchQueue.main.async { view.window?.makeFirstResponder(view) }
        return view
    }
    func updateNSView(_ nsView: GhosttyMacSurface, context: Context) {}
}
